# Generated by Django 2.0.5 on 2018-06-03 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstrosatSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('LOCAL', 'LOCAL'), ('TEST', 'TEST'), ('DEV', 'DEV'), ('PROD', 'PROD')], max_length=128)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='astrosat_site', to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'Astrosat Sites',
                'verbose_name': 'Astrosat Site',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(max_length=256, verbose_name='Center')),
                ('center_search_status', models.CharField(max_length=256, verbose_name='Center Search Status')),
                ('facility', models.CharField(max_length=256, verbose_name='Facility')),
                ('facilityurl', models.URLField(verbose_name='FacilityURL')),
                ('occupied', models.DateTimeField(null=True, verbose_name='Occupied')),
                ('status', models.CharField(max_length=256, verbose_name='status')),
                ('url_link', models.URLField(verbose_name='URL Link')),
                ('record_date', models.DateTimeField(null=True, verbose_name='Record Date')),
                ('last_update', models.DateTimeField(null=True, verbose_name='Last Update')),
                ('country', models.CharField(max_length=256, verbose_name='Country')),
                ('contact', models.CharField(max_length=256, verbose_name='Contact')),
                ('phone', models.CharField(max_length=256, verbose_name='Phone')),
                ('city', models.CharField(max_length=256, verbose_name='City')),
                ('state', models.CharField(max_length=256, verbose_name='State')),
                ('zipcode', models.CharField(max_length=256, verbose_name='Zipcode')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'NASA Facilities',
                'verbose_name': 'NASA Facility',
            },
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('center', 'facility')},
        ),
    ]
